language: python

python:
  - 3.6

services:
  - docker

before_install:
  - npm install aglio
  - docker-compose -f local/compose.yml -p imgm up -d
  - docker build -t ${TRAVIS_REPO_SLUG} .
  - docker tag ${TRAVIS_REPO_SLUG} local/imagemanager:latest
  - docker build -f tests/Dockerfile -t local/db_fixture .
  - docker run -d --network imgm_default --network-alias image-manager ${TRAVIS_REPO_SLUG}

script:
  - docker run --network imgm_default local/db_fixture

after_success:
  - travis/publish.sh
  - travis/deploy-gh-pages.sh
