sudo: required

language: python

python:
  - "3.5"

services:
  - docker

before_install:
- docker-compose -f local/compose.yml -p imgm up -d
- docker build -f Dockerfile -t local/imagemanager .
- docker build -f tests/Dockerfile -t local/db_fixture .
- docker run -d --network imgm_default --network-alias image-manager local/imagemanager

script:
- docker run --network imgm_default local/db_fixture
